# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Para < Formula
  desc "A useful tool for software package manager analytics."
  homepage "https://github.com/felicianotech/para"
  version "0.5.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felicianotech/para/releases/download/v0.5.0/para-v0.5.0-macos-amd64.tar.gz"
      sha256 "fb6d68c5a6c0e162ef7ce27201074102b19840329d076565ce2ce398c5c71967"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/felicianotech/para/releases/download/v0.5.0/para-v0.5.0-linux-amd64.tar.gz"
      sha256 "f152fdc4c7538c8c19b987e4494dc4a8084dbf74c55120d8f1201548c3eb384f"
    end
  end

  def install
    bin.install "para"
  end

  test do
    system "#{bin}/para", "help"
  end
end
