# This file was generated by GoReleaser. DO NOT EDIT.
class Sonar < Formula
  desc "A Docker utility."
  homepage "https://github.com/felicianotech/sonar"
  version "0.13.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/felicianotech/sonar/releases/download/v0.13.1/sonar-v0.13.1-macos-amd64.tar.gz"
    sha256 "0f9fb5c444ab8143f89a93078b3be658cb09e94281d9ae321b2209c36a4555f0"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/felicianotech/sonar/releases/download/v0.13.1/sonar-v0.13.1-linux-amd64.tar.gz"
    sha256 "f1c627a3e9ad59b1b2bbde9851e8cbe2b1dfd339e7fd02fe2a73667f70511bca"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/felicianotech/sonar/releases/download/v0.13.1/sonar-v0.13.1-linux-arm64.tar.gz"
    sha256 "a4890a55f67bf29583971a71906df9365a3763143ce0af91c4b54e04ca26a5cf"
  end

  def install
    bin.install "sonar"
  end

  test do
    system "#{bin}/sonar", "help"
  end
end
