# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Valerie < Formula
  desc "An HTML schema validator."
  homepage "https://github.com/felicianotech/valerie"
  version "0.1.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/felicianotech/valerie/releases/download/v0.1.0/valerie-v0.1.0-macos-amd64.tar.gz"
    sha256 "8c8df87fb79beb06b83f9109d2a0dda20446089d0f5c3b907d2e36963b171af1"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/felicianotech/valerie/releases/download/v0.1.0/valerie-v0.1.0-macos-arm64.tar.gz"
    sha256 "72d3ff857b45f94b39961b4157dba4687888aaf58503b0944a78ba138125096c"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/felicianotech/valerie/releases/download/v0.1.0/valerie-v0.1.0-linux-amd64.tar.gz"
    sha256 "97157b049b919b4acc9c5f3b58e4df49675f27f2ac9c29e6168bbbeb570bbc1d"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/felicianotech/valerie/releases/download/v0.1.0/valerie-v0.1.0-linux-arm64.tar.gz"
    sha256 "26e9686e98fbe718397544c41351bcb779246012fc2c5d38991adc20cad24ac9"
  end

  def install
    bin.install "valerie"
  end

  test do
    system "#{bin}/valerie", "help"
  end
end
