# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Valerie < Formula
  desc "An HTML schema validator."
  homepage "https://github.com/felicianotech/valerie"
  version "0.2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felicianotech/valerie/releases/download/v0.2.0/valerie-v0.2.0-macos-amd64.tar.gz"
      sha256 "47a0679ffbfb46ddaca102551922f3ad613691e24f332799ad2609c7b27e35c6"
    end
    if Hardware::CPU.arm?
      url "https://github.com/felicianotech/valerie/releases/download/v0.2.0/valerie-v0.2.0-macos-arm64.tar.gz"
      sha256 "525a97d3a56b9ad650a3ada0edbdd7a8752d291005200729b3484a28f8c42572"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/felicianotech/valerie/releases/download/v0.2.0/valerie-v0.2.0-linux-amd64.tar.gz"
      sha256 "87a198d6e320e9520a673a18c3e817851d3407d4990c1fe2454fcdbef1358e0f"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felicianotech/valerie/releases/download/v0.2.0/valerie-v0.2.0-linux-arm64.tar.gz"
      sha256 "ef00537e9e754085bd21bdaabb6dc768285fe839cf8282445510f33e69917eec"
    end
  end

  def install
    bin.install "valerie"
  end

  test do
    system "#{bin}/valerie", "help"
  end
end
