# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Warden < Formula
  desc "Audit your git repositories based on policy."
  homepage "https://RepoWarden.com"
  version "0.1.0-alpha.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/repowarden/cli/releases/download/v0.1.0-alpha.2/warden-v0.1.0-alpha.2-macos-arm64.tar.gz"
      sha256 "ae0a0265c28273e3e3801e35c2e303b5835ef61cf6a74f4039dfff8730a76792"

      def install
        bin.install "warden"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/repowarden/cli/releases/download/v0.1.0-alpha.2/warden-v0.1.0-alpha.2-macos-amd64.tar.gz"
      sha256 "f50df781c4d1f7fd248c31500c048513daa4a938757c3d4fd7f0ac0c3515b334"

      def install
        bin.install "warden"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/repowarden/cli/releases/download/v0.1.0-alpha.2/warden-v0.1.0-alpha.2-linux-arm64.tar.gz"
      sha256 "c387a7dab762556665816a589e706c176439e8526ed4d298f5019857b0488183"

      def install
        bin.install "warden"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/repowarden/cli/releases/download/v0.1.0-alpha.2/warden-v0.1.0-alpha.2-linux-amd64.tar.gz"
      sha256 "8953630d5605b7c7db966eb75287f72863454cf5d5c04ff44dfe723fee84a3f0"

      def install
        bin.install "warden"
      end
    end
  end

  test do
    system "#{bin}/warden", "help"
  end
end
