# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Warden < Formula
  desc "Audit your git repositories based on policy."
  homepage "https://RepoWarden.com"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/repowarden/cli/releases/download/v0.2.0/warden-v0.2.0-macos-arm64.tar.gz"
      sha256 "50545ee19a860d7284ad4fc488bb238995cb4eb353d27da5283a3a99f1a776e0"

      def install
        bin.install "warden"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/repowarden/cli/releases/download/v0.2.0/warden-v0.2.0-macos-amd64.tar.gz"
      sha256 "5b89b29623f1f303fad2601b060d073891275f8cafe0159f58bc56b82cb446ef"

      def install
        bin.install "warden"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/repowarden/cli/releases/download/v0.2.0/warden-v0.2.0-linux-arm64.tar.gz"
      sha256 "72a8253562b3a69d02842ebc2c07bce378741b58e459cf3aa13838ef752d1939"

      def install
        bin.install "warden"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/repowarden/cli/releases/download/v0.2.0/warden-v0.2.0-linux-amd64.tar.gz"
      sha256 "f1f1d8cce63a9e2961a1cda7bcae376f66da583087a6f31a53a8e9a95362bd13"

      def install
        bin.install "warden"
      end
    end
  end

  test do
    system "#{bin}/warden", "help"
  end
end
